authors:
  zhangyan:
    name: Zhang, Y
    description: Fellow
    avatar: https://avatars.githubusercontent.com/u/22789554?v=4
    url: https://github.com/yemanzhongting
  mw:
    name: Mao, W
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/18610440?s=400&u=bd04a4308341648feb80e4fc9cdc4c38914a7f72&v=4
    url: https://github.com/Weiwei-Mao
  gaoming:
    name: Ming,G
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/18610440?s=400&u=bd04a4308341648feb80e4fc9cdc4c38914a7f72&v=4
    url: https://github.com/Weiwei-Mao