authors:
  Author1:
    name: Author1
    description: Description
    avatar: assets/photo1.png
    url: https://github.com/***
  Author2:
    name: Author2
    description: Description
    avatar: assets/photo2.png
    url: https://github.com/***
